#!/usr/bin/env bats

# P119: manage-problem-enforce-create.sh PreToolUse hook must block new-file
# Write to docs/problems/<NNN>-*.<status>.md until /wr-itil:manage-problem
# Step 2 (duplicate-check) has run for the current session.
#
# Marker: /tmp/manage-problem-grep-${SESSION_ID} (set by Step 2 grep
# completion). Per-session scope so a single skill invocation can write
# multiple tickets (Step 4b multi-concern split) without re-grep blocking.
#
# Per feedback_behavioural_tests.md (P081): behavioural assertions —
# simulate the hook's payload on stdin and assert on emitted JSON
# permissionDecision and exit status. No source-grep on hook content.
#
# ADR-031 forward-compat: matcher uses docs/problems/ prefix +
# numeric-prefix basename test, agnostic to current suffix-based
# layout vs future per-state subdirectory layout.

setup() {
  SCRIPT_DIR="$(cd "$(dirname "$BATS_TEST_FILENAME")/.." && pwd)"
  HOOK="$SCRIPT_DIR/manage-problem-enforce-create.sh"
  ORIG_DIR="$PWD"
  TEST_DIR=$(mktemp -d)
  cd "$TEST_DIR"
  mkdir -p docs/problems docs/rfcs
  SID="mp-create-test-$$-$RANDOM"
}

teardown() {
  cd "$ORIG_DIR"
  rm -rf "$TEST_DIR"
  rm -f "/tmp/manage-problem-grep-${SID}"
  rm -f "/tmp/wr-itil-rfc-capture-grep-${SID}"
}

set_rfc_marker() {
  : > "/tmp/wr-itil-rfc-capture-grep-${SID}"
}

# Helper: run the hook with mock JSON for a Write tool call to file_path
run_write_hook() {
  local file_path="$1"
  local sid="$2"
  local json
  json=$(printf '{"tool_name":"Write","tool_input":{"file_path":"%s"},"session_id":"%s"}' "$file_path" "$sid")
  echo "$json" | bash "$HOOK"
}

# Helper: run the hook with mock JSON for an Edit tool call to file_path
run_edit_hook() {
  local file_path="$1"
  local sid="$2"
  local json
  json=$(printf '{"tool_name":"Edit","tool_input":{"file_path":"%s"},"session_id":"%s"}' "$file_path" "$sid")
  echo "$json" | bash "$HOOK"
}

set_marker() {
  : > "/tmp/manage-problem-grep-${SID}"
}

# --- Core deny path: new-file Write without marker ---

@test "deny: Write to new docs/problems/999-foo.open.md without marker" {
  run run_write_hook "$PWD/docs/problems/999-foo.open.md" "$SID"
  [ "$status" -eq 0 ]
  [[ "$output" == *"\"permissionDecision\": \"deny\""* ]]
  [[ "$output" == *"BLOCKED"* ]]
  [[ "$output" == *"manage-problem"* ]]
}

@test "deny message names the skill the agent must invoke" {
  run run_write_hook "$PWD/docs/problems/999-foo.open.md" "$SID"
  [ "$status" -eq 0 ]
  [[ "$output" == *"/wr-itil:manage-problem"* ]]
}

# --- Allow paths ---

@test "allow: Write to new docs/problems/999-foo.open.md WITH marker" {
  set_marker
  run run_write_hook "$PWD/docs/problems/999-foo.open.md" "$SID"
  [ "$status" -eq 0 ]
  [[ "$output" != *"BLOCKED"* ]]
  [[ "$output" != *"\"permissionDecision\": \"deny\""* ]]
}

@test "allow: marker permits multiple consecutive Writes (multi-concern split, Step 4b)" {
  set_marker
  run run_write_hook "$PWD/docs/problems/998-foo.open.md" "$SID"
  [ "$status" -eq 0 ]
  [[ "$output" != *"BLOCKED"* ]]
  run run_write_hook "$PWD/docs/problems/999-bar.open.md" "$SID"
  [ "$status" -eq 0 ]
  [[ "$output" != *"BLOCKED"* ]]
}

@test "allow: Write to docs/problems/README.md regardless of marker" {
  # README is regenerated by Steps 5/6/7 — chicken-and-egg per ticket Out of Scope
  run run_write_hook "$PWD/docs/problems/README.md" "$SID"
  [ "$status" -eq 0 ]
  [[ "$output" != *"BLOCKED"* ]]
}

@test "allow: Edit (not Write) to existing ticket regardless of marker" {
  echo "stub" > docs/problems/042-existing.open.md
  run run_edit_hook "$PWD/docs/problems/042-existing.open.md" "$SID"
  [ "$status" -eq 0 ]
  [[ "$output" != *"BLOCKED"* ]]
}

@test "allow: Write to existing ticket file (overwrite) regardless of marker" {
  # Existing file = not a new ticket creation — Edit-flow / status transitions
  # are governed by /wr-itil:transition-problem, not this hook.
  echo "stub" > docs/problems/042-existing.open.md
  run run_write_hook "$PWD/docs/problems/042-existing.open.md" "$SID"
  [ "$status" -eq 0 ]
  [[ "$output" != *"BLOCKED"* ]]
}

@test "allow: Write to non-docs/problems path regardless of marker" {
  run run_write_hook "$PWD/src/component.tsx" "$SID"
  [ "$status" -eq 0 ]
  [[ "$output" != *"BLOCKED"* ]]
}

@test "allow: Write to docs/problems/ non-numeric basename (e.g. NOTES.md)" {
  # Only docs/problems/<NNN>-*.md ticket-shaped paths are gated. Other
  # docs in this directory (e.g. NOTES.md, archive/index.md) are not
  # tickets and don't need the duplicate-check.
  run run_write_hook "$PWD/docs/problems/NOTES.md" "$SID"
  [ "$status" -eq 0 ]
  [[ "$output" != *"BLOCKED"* ]]
}

# --- Status-suffix coverage (ADR-022 lifecycle) ---

@test "deny: new .known-error.md without marker" {
  run run_write_hook "$PWD/docs/problems/999-foo.known-error.md" "$SID"
  [ "$status" -eq 0 ]
  [[ "$output" == *"BLOCKED"* ]]
}

@test "deny: new .verifying.md without marker" {
  run run_write_hook "$PWD/docs/problems/999-foo.verifying.md" "$SID"
  [ "$status" -eq 0 ]
  [[ "$output" == *"BLOCKED"* ]]
}

@test "deny: new .parked.md without marker" {
  run run_write_hook "$PWD/docs/problems/999-foo.parked.md" "$SID"
  [ "$status" -eq 0 ]
  [[ "$output" == *"BLOCKED"* ]]
}

# --- Tool-name and edge cases ---

@test "allow: empty session_id (fail-open for parse failure parity with sibling hooks)" {
  # Mirror jtbd-enforce-edit.sh: empty session_id => exit 0 without deny.
  run bash -c "echo '{\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"$PWD/docs/problems/999-foo.open.md\"}}' | bash $HOOK"
  [ "$status" -eq 0 ]
  # No deny — empty session is the parse-error / fallback shape
  [[ "$output" != *"\"permissionDecision\": \"deny\""* ]] || skip "fail-closed parse error is also acceptable; assert in parse-failure test"
}

@test "allow: empty file_path exits 0 without action" {
  run bash -c "echo '{\"tool_name\":\"Write\",\"tool_input\":{},\"session_id\":\"$SID\"}' | bash $HOOK"
  [ "$status" -eq 0 ]
  [[ "$output" != *"BLOCKED"* ]]
}

# --- ADR-031 forward-compat: per-state subdirectory shape ---

@test "deny: hypothetical ADR-031 layout docs/problems/open/999-foo.md without marker" {
  # If/when ADR-031 lands and tickets move to docs/problems/<state>/<NNN>-...md,
  # the hook must still gate them. Matcher should be path-prefix +
  # numeric-prefix basename, not suffix-based.
  mkdir -p docs/problems/open
  run run_write_hook "$PWD/docs/problems/open/999-foo.md" "$SID"
  [ "$status" -eq 0 ]
  [[ "$output" == *"BLOCKED"* ]]
}

# --- Marker hygiene ---

@test "marker file presence is the gate signal — touching marker after first deny unblocks subsequent Write" {
  run run_write_hook "$PWD/docs/problems/999-foo.open.md" "$SID"
  [[ "$output" == *"BLOCKED"* ]]
  set_marker
  run run_write_hook "$PWD/docs/problems/999-foo.open.md" "$SID"
  [ "$status" -eq 0 ]
  [[ "$output" != *"BLOCKED"* ]]
}

# --- P142 / ADR-050: deny-message simplicity post-supersession ---
#
# ADR-048 documented a two-tier recovery procedure for SID-mismatch denials
# (when the helper picked a stale subprocess SID while the runtime hook saw
# the orchestrator SID). The hook appended a "Helper succeeded but SID
# mismatch detected — see manage-problem SKILL.md Step 2 substep 7."
# pointer when SOME marker existed for SOME SID (the helper-bug signal).
#
# P142 / ADR-050 superseded ADR-048 by capturing the runtime stdin SID
# in a per-machine marker via a new PreToolUse hook
# (`itil-runtime-sid-marker.sh`). The helper reads the marker as
# authoritative; SID-mismatch is structurally impossible in routine flow.
# The conditional RECOVERY_HINT was removed; the deny message stays
# terse and skill-pointing regardless of marker presence.
#
# These tests pin that the deny message is INVARIANT of the
# /tmp/manage-problem-grep-* marker state (no recovery-hint branching).

setup_other_sid_marker() {
  OTHER_SID="other-sid-$$-$RANDOM"
  : > "/tmp/manage-problem-grep-${OTHER_SID}"
}

teardown_other_sid_marker() {
  if [ -n "${OTHER_SID:-}" ]; then
    rm -f "/tmp/manage-problem-grep-${OTHER_SID}"
  fi
}

@test "deny without ANY /tmp/manage-problem-grep-* marker → deny is terse, no recovery prose" {
  rm -f /tmp/manage-problem-grep-*
  run run_write_hook "$PWD/docs/problems/999-foo.open.md" "$SID"
  [ "$status" -eq 0 ]
  [[ "$output" == *"BLOCKED"* ]]
  [[ "$output" != *"SID mismatch"* ]]
  [[ "$output" != *"Step 2 substep 7"* ]]
}

@test "deny with /tmp/manage-problem-grep-* marker for OTHER SID → deny is terse (post-ADR-050; no recovery hint)" {
  # Pre-ADR-050 contract: an other-SID marker triggered the helper-bug
  # recovery pointer. Post-ADR-050: the runtime-SID marker prevents
  # SID-mismatch in routine flow, so the recovery pointer is removed.
  # The deny message is identical regardless of marker presence — the
  # only signal that matters is "this session has not run Step 2".
  rm -f /tmp/manage-problem-grep-*
  setup_other_sid_marker
  run run_write_hook "$PWD/docs/problems/999-foo.open.md" "$SID"
  status=$?
  teardown_other_sid_marker
  [ "$status" -eq 0 ]
  [[ "$output" == *"BLOCKED"* ]]
  [[ "$output" != *"SID mismatch"* ]]
  [[ "$output" != *"Step 2 substep 7"* ]]
}

# --- P170 / ADR-060: RFC tier extension ---
#
# The hook gate covers both docs/problems/ and docs/rfcs/. Each tier has its
# own marker (problems: /tmp/manage-problem-grep-${SID};
# rfcs: /tmp/wr-itil-rfc-capture-grep-${SID}) and its own deny message
# pointing to the right skill (manage-problem vs capture-rfc).

@test "rfcs deny: Write to new docs/rfcs/RFC-001-foo.proposed.md without RFC marker" {
  run run_write_hook "$PWD/docs/rfcs/RFC-001-foo.proposed.md" "$SID"
  [ "$status" -eq 0 ]
  [[ "$output" == *"\"permissionDecision\": \"deny\""* ]]
  [[ "$output" == *"BLOCKED"* ]]
}

@test "rfcs deny message names capture-rfc skill (not manage-problem)" {
  run run_write_hook "$PWD/docs/rfcs/RFC-001-foo.proposed.md" "$SID"
  [ "$status" -eq 0 ]
  [[ "$output" == *"/wr-itil:capture-rfc"* ]]
  [[ "$output" != *"/wr-itil:manage-problem"* ]]
}

@test "rfcs deny message names the I1 trace-to-problem invariant + ADR-060" {
  run run_write_hook "$PWD/docs/rfcs/RFC-001-foo.proposed.md" "$SID"
  [ "$status" -eq 0 ]
  [[ "$output" == *"problem-trace"* ]]
  [[ "$output" == *"ADR-060"* ]]
}

@test "rfcs allow: Write to new docs/rfcs/RFC-001-foo.proposed.md WITH RFC marker" {
  set_rfc_marker
  run run_write_hook "$PWD/docs/rfcs/RFC-001-foo.proposed.md" "$SID"
  [ "$status" -eq 0 ]
  [[ "$output" != *"BLOCKED"* ]]
  [[ "$output" != *"\"permissionDecision\": \"deny\""* ]]
}

@test "rfcs allow: Write to docs/rfcs/README.md regardless of marker (chicken-and-egg)" {
  run run_write_hook "$PWD/docs/rfcs/README.md" "$SID"
  [ "$status" -eq 0 ]
  [[ "$output" != *"BLOCKED"* ]]
}

@test "rfcs allow: Write to docs/rfcs/ non-RFC basename (e.g. NOTES.md) regardless of marker" {
  run run_write_hook "$PWD/docs/rfcs/NOTES.md" "$SID"
  [ "$status" -eq 0 ]
  [[ "$output" != *"BLOCKED"* ]]
}

@test "rfcs deny: Write across all RFC lifecycle suffixes without marker (proposed/accepted/in-progress/verifying/closed)" {
  for suffix in proposed accepted in-progress verifying closed; do
    run run_write_hook "$PWD/docs/rfcs/RFC-001-foo.${suffix}.md" "$SID"
    [ "$status" -eq 0 ]
    [[ "$output" == *"BLOCKED"* ]] || { echo "expected deny for suffix=$suffix"; return 1; }
  done
}

@test "rfcs marker independence: problem marker does NOT unlock RFC writes" {
  # The two markers are siblings, not interchangeable. Setting the
  # problem-tier marker should NOT bypass the RFC-tier gate.
  set_marker
  run run_write_hook "$PWD/docs/rfcs/RFC-001-foo.proposed.md" "$SID"
  [ "$status" -eq 0 ]
  [[ "$output" == *"BLOCKED"* ]]
  [[ "$output" == *"capture-rfc"* ]]
}

@test "problems marker independence: RFC marker does NOT unlock problem writes" {
  # Inverse direction — preserves audit-trail per-surface granularity.
  set_rfc_marker
  run run_write_hook "$PWD/docs/problems/999-foo.open.md" "$SID"
  [ "$status" -eq 0 ]
  [[ "$output" == *"BLOCKED"* ]]
  [[ "$output" == *"manage-problem"* ]]
}

@test "rfcs allow: existing RFC file (overwrite) regardless of marker" {
  echo "stub" > docs/rfcs/RFC-001-foo.proposed.md
  run run_write_hook "$PWD/docs/rfcs/RFC-001-foo.proposed.md" "$SID"
  [ "$status" -eq 0 ]
  [[ "$output" != *"BLOCKED"* ]]
}

@test "rfcs allow: Edit (not Write) regardless of marker" {
  echo "stub" > docs/rfcs/RFC-001-foo.proposed.md
  run run_edit_hook "$PWD/docs/rfcs/RFC-001-foo.proposed.md" "$SID"
  [ "$status" -eq 0 ]
  [[ "$output" != *"BLOCKED"* ]]
}

@test "rfcs deny: bare numeric basename (no RFC- prefix) does NOT match the rfcs gate" {
  # Defensive: a docs/rfcs/123-foo.proposed.md (no RFC- prefix) is not
  # an RFC by naming convention; it should NOT trigger the gate.
  # (If the user accidentally creates such a file, it's project
  # housekeeping, not a ticket.)
  run run_write_hook "$PWD/docs/rfcs/123-no-prefix.proposed.md" "$SID"
  [ "$status" -eq 0 ]
  [[ "$output" != *"BLOCKED"* ]]
}
