#!/bin/bash
# P119: PreToolUse:Write enforcement hook for new problem ticket creation.
#
# BLOCKS Write to docs/problems/<NNN>-*.<status>.md when the file does not
# yet exist on disk and the per-session Step-2 grep marker is absent.
# Marker is set by /wr-itil:manage-problem Step 2 (duplicate-check) at the
# end of its grep pass — present marker means the agent has run the
# duplicate-check for this session and may write new tickets.
#
# Out of scope (allow-listed):
#   - docs/problems/README.md  — regenerated by Steps 5/6/7 (chicken-and-egg)
#   - Existing files           — Edit-flow / status transitions are
#                                governed by /wr-itil:transition-problem,
#                                not new-ticket creation
#   - Edit tool                — only Write is gated; Edit on existing
#                                tickets is normal status-transition shape
#   - Non-ticket basenames     — only docs/problems/<NNN>-*.md ticket-shaped
#                                paths are gated (NOTES.md, archive/, etc.
#                                are project housekeeping, not tickets)
#
# ADR-031 forward-compat: matcher uses docs/problems/ prefix + numeric
# basename, agnostic to current suffix-based layout (docs/problems/NNN-*.<status>.md)
# vs. future per-state subdirectory layout (docs/problems/<state>/NNN-*.md).
#
# References:
#   ADR-009 — gate marker lifecycle (per-session /tmp markers).
#   ADR-013 Rule 1 — deny redirects to /wr-itil:manage-problem where
#                    Step 2 fires AskUserQuestion if duplicates exist.
#   ADR-022 — problem lifecycle (status suffixes covered: open / known-error /
#             verifying / parked).
#   ADR-038 — progressive disclosure (deny message stays terse + actionable).
#   P119    — agent bypasses Step 2 by writing tickets directly.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=lib/create-gate.sh
source "$SCRIPT_DIR/lib/create-gate.sh"

INPUT=$(cat)

TOOL_NAME=$(echo "$INPUT" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    print(data.get('tool_name', ''))
except:
    print('')
" 2>/dev/null || echo "")

FILE_PATH=$(echo "$INPUT" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    print(data.get('tool_input', {}).get('file_path', ''))
except:
    print('')
" 2>/dev/null || echo "")

SESSION_ID=$(echo "$INPUT" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    print(data.get('session_id', ''))
except:
    print('')
" 2>/dev/null || echo "")

# Only gate the Write tool. Edit on existing tickets is the
# transition-problem surface, not the new-ticket surface.
if [ "$TOOL_NAME" != "Write" ]; then
  exit 0
fi

# Empty file_path or session_id — fail-open (mirror jtbd-enforce-edit.sh).
# Empty session_id with a real file_path could be a hook harness call;
# do not deny on parse-incomplete input.
if [ -z "$FILE_PATH" ]; then
  exit 0
fi

if [ -z "$SESSION_ID" ]; then
  exit 0
fi

# Match docs/problems/ paths only. Both absolute (project-root prefixed)
# and relative shapes are accepted because Claude Code passes absolute
# paths in tool_input.file_path but tests and direct invocations may
# use relative paths.
case "$FILE_PATH" in
  *docs/problems/*) ;;
  *) exit 0 ;;
esac

BASENAME=$(basename "$FILE_PATH")

# Allow-list: docs/problems/README.md is regenerated by Steps 5/6/7.
# Gating it would chicken-and-egg the skill itself.
if [ "$BASENAME" = "README.md" ]; then
  exit 0
fi

# Only gate ticket-shaped basenames: NNN-... (3-digit prefix).
# Non-ticket files (NOTES.md, archive/index.md, etc.) are project
# housekeeping and don't need the duplicate-check.
case "$BASENAME" in
  [0-9][0-9][0-9]-*) ;;
  *) exit 0 ;;
esac

# Existing file — Edit-flow / status-transition path. Only block
# new-file creation (the Write that materialises a brand-new ticket).
if [ -f "$FILE_PATH" ]; then
  exit 0
fi

# New ticket Write: gate on the Step-2 grep marker.
if check_create_gate "$SESSION_ID"; then
  exit 0
fi

# P142 / ADR-050: the runtime-SID instrumentation hook
# (itil-runtime-sid-marker.sh) writes the runtime stdin session_id to a
# per-machine marker on every PreToolUse:Bash|Write|Edit|Read event. The
# `get_current_session_id` helper reads that marker as the authoritative
# SID, so the marker `mark_step2_complete` writes is bound to the same
# session_id this hook will see on the subsequent Write. SID-mismatch
# denial is structurally eliminated; the only remaining deny path is
# the routine "Step 2 grep has not run yet for this session" case, for
# which the deny message stays focused and skill-pointing.
create_gate_deny "BLOCKED: Cannot Write '${BASENAME}' under docs/problems/ without running /wr-itil:manage-problem Step 2 (duplicate-check) first. New problem tickets MUST be created via the skill so the duplicate-prevention grep fires before the file lands. Invoke the Skill tool with skill='wr-itil:manage-problem' and a description of the new problem; Step 2 will grep for related existing tickets and surface any matches via AskUserQuestion before creating the new ticket. (P119)"
exit 0
